name: Deploy Next.js App to HostAtom (Production)

on:
  push:
    branches:
      - main
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build:root
        env:
          NODE_ENV: production

      - name: Create Restart Trigger File
        run: |
          mkdir -p tmp
          touch tmp/restart.txt

      - name: Deploy to HostAtom via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ftp.checkkub.com
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./
          server-dir: domains/checkkub.com/public_html/
          dangerous-clean-slate: false
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            **/.DS_Store
            **/src/**
            **/.vscode/**
            **/scripts/**
            .env*.local
            .env
            README.md
            package-lock.json
